from typing import List, Dict, Any


def generate_aws_terraform(resources: List[Dict[str, Any]]) -> str:
    lines = [
        '# ============================================================',
        '# AUTOMATICALLY GENERATED BY CLOUDMOVE MIGRATION ENGINE',
        '# ZERO HARDCODED ARCHITECTURE · DYNAMIC IAC GENERATION',
        '# ============================================================',
        '',
        'terraform {',
        '  required_version = ">= 1.5.0"',
        '  required_providers {',
        '    aws = {',
        '      source  = "hashicorp/aws"',
        '      version = "~> 5.0"',
        '    }',
        '  }',
        '}',
        '',
        'provider "aws" {',
        '  region = var.aws_region',
        '}',
        '',
        'variable "aws_region" {',
        '  description = "Target AWS Region"',
        '  type        = string',
        '  default     = "us-east-1"',
        '}',
        '',
        'variable "environment" {',
        '  description = "Target Deployment Environment"',
        '  type        = string',
        '  default     = "production"',
        '}',
        '',
        'variable "vpc_cidr" {',
        '  description = "CIDR block for the target VPC"',
        '  type        = string',
        '  default     = "10.0.0.0/16"',
        '}',
        '',
        'variable "db_password" {',
        '  description = "Database Master Password (Sensitive)"',
        '  type        = string',
        '  sensitive   = true',
        '  default     = "ChangeMeInProduction123!"',
        '}',
        '',
    ]

    has_network = any(r.get("cmir_type") in ("network", "vpc") for r in resources)
    has_compute = any(r.get("cmir_type") in ("compute", "workload", "service", "application", "container") for r in resources)
    has_db = any(r.get("cmir_type") == "database" for r in resources)
    has_cache = any(r.get("cmir_type") == "cache" for r in resources)
    has_storage = any(r.get("cmir_type") in ("storage", "bucket") for r in resources)

    # Base Network Infrastructure
    lines.extend([
        '# ------------------------------------------------------------',
        '# Network & Isolation Boundaries',
        '# ------------------------------------------------------------',
        'resource "aws_vpc" "target_vpc" {',
        '  cidr_block           = var.vpc_cidr',
        '  enable_dns_support   = true',
        '  enable_dns_hostnames = true',
        '  tags = {',
        '    Name        = "cloudmove-target-vpc"',
        '    Environment = var.environment',
        '  }',
        '}',
        '',
        'resource "aws_internet_gateway" "igw" {',
        '  vpc_id = aws_vpc.target_vpc.id',
        '  tags = {',
        '    Name = "cloudmove-igw"',
        '  }',
        '}',
        '',
        'resource "aws_subnet" "public_subnet" {',
        '  vpc_id                  = aws_vpc.target_vpc.id',
        '  cidr_block              = "10.0.1.0/24"',
        '  map_public_ip_on_launch = true',
        '  tags = {',
        '    Name = "cloudmove-public-subnet"',
        '  }',
        '}',
        '',
        'resource "aws_subnet" "private_subnet_a" {',
        '  vpc_id            = aws_vpc.target_vpc.id',
        '  cidr_block        = "10.0.2.0/24"',
        '  availability_zone = "${var.aws_region}a"',
        '  tags = {',
        '    Name = "cloudmove-private-subnet-a"',
        '  }',
        '}',
        '',
        'resource "aws_subnet" "private_subnet_b" {',
        '  vpc_id            = aws_vpc.target_vpc.id',
        '  cidr_block        = "10.0.3.0/24"',
        '  availability_zone = "${var.aws_region}b"',
        '  tags = {',
        '    Name = "cloudmove-private-subnet-b"',
        '  }',
        '}',
        '',
        'resource "aws_security_group" "app_sg" {',
        '  name        = "cloudmove-app-sg"',
        '  description = "Security group for migrated application workloads"',
        '  vpc_id      = aws_vpc.target_vpc.id',
        '  ingress {',
        '    from_port   = 80',
        '    to_port     = 80',
        '    protocol    = "tcp"',
        '    cidr_blocks = ["0.0.0.0/0"]',
        '  }',
        '  ingress {',
        '    from_port   = 443',
        '    to_port     = 443',
        '    protocol    = "tcp"',
        '    cidr_blocks = ["0.0.0.0/0"]',
        '  }',
        '  egress {',
        '    from_port   = 0',
        '    to_port     = 0',
        '    protocol    = "-1"',
        '    cidr_blocks = ["0.0.0.0/0"]',
        '  }',
        '  tags = {',
        '    Name = "cloudmove-app-sg"',
        '  }',
        '}',
        '',
    ])

    if has_db or has_cache:
        lines.extend([
            'resource "aws_security_group" "data_sg" {',
            '  name        = "cloudmove-data-sg"',
            '  description = "Security group for migrated data services"',
            '  vpc_id      = aws_vpc.target_vpc.id',
            '  ingress {',
            '    from_port       = 5432',
            '    to_port         = 5432',
            '    protocol        = "tcp"',
            '    security_groups = [aws_security_group.app_sg.id]',
            '  }',
            '  ingress {',
            '    from_port       = 6379',
            '    to_port         = 6379',
            '    protocol        = "tcp"',
            '    security_groups = [aws_security_group.app_sg.id]',
            '  }',
            '  egress {',
            '    from_port   = 0',
            '    to_port     = 0',
            '    protocol    = "-1"',
            '    cidr_blocks = ["0.0.0.0/0"]',
            '  }',
            '  tags = {',
            '    Name = "cloudmove-data-sg"',
            '  }',
            '}',
            '',
            'resource "aws_db_subnet_group" "db_subnets" {',
            '  name       = "cloudmove-db-subnets"',
            '  subnet_ids = [aws_subnet.private_subnet_a.id, aws_subnet.private_subnet_b.id]',
            '  tags = {',
            '    Name = "cloudmove-db-subnets"',
            '  }',
            '}',
            '',
        ])

    # Dynamic generation per resource
    lines.append('# ------------------------------------------------------------')
    lines.append('# Migrated Target Resources (Dynamic Specs)')
    lines.append('# ------------------------------------------------------------')

    for r in resources:
        r_id = r.get("safe_id", r.get("id").replace("-", "_"))
        r_name = r.get("safe_name", r.get("name"))
        r_type = r.get("type", "aws_instance")
        cmir_type = r.get("cmir_type", "workload")
        engine = r.get("engine", "postgres")

        lines.append(f'# Resource: {r.get("name")} ({r.get("id")})')

        if r_type == "aws_instance":
            lines.extend([
                f'resource "aws_instance" "{r_id}" {{',
                '  ami                         = "ami-0c55b159cbfafe1f0"',
                '  instance_type               = "t3.micro"',
                '  subnet_id                   = aws_subnet.public_subnet.id',
                '  vpc_security_group_ids     = [aws_security_group.app_sg.id]',
                '  associate_public_ip_address = true',
                '  tags = {',
                f'    Name        = "{r_name}"',
                f'    CMIR_ID     = "{r.get("id")}"',
                '    ManagedBy   = "CloudMove"',
                '  }',
                '}',
                '',
            ])
        elif r_type == "aws_db_instance":
            db_engine = "postgres" if "postg" in str(engine).lower() else "mysql" if "mysql" in str(engine).lower() else "postgres"
            lines.extend([
                f'resource "aws_db_instance" "{r_id}" {{',
                f'  identifier             = "{r_name}"',
                f'  engine                 = "{db_engine}"',
                '  instance_class         = "db.t3.micro"',
                '  allocated_storage      = 20',
                '  username               = "cloudmove_admin"',
                '  password               = var.db_password',
                '  publicly_accessible    = false',
                '  skip_final_snapshot    = true',
                '  db_subnet_group_name   = aws_db_subnet_group.db_subnets.name',
                '  vpc_security_group_ids  = [aws_security_group.data_sg.id]',
                '  tags = {',
                f'    Name        = "{r_name}"',
                f'    CMIR_ID     = "{r.get("id")}"',
                '    ManagedBy   = "CloudMove"',
                '  }',
                '}',
                '',
            ])
        elif r_type == "aws_elasticache_cluster":
            lines.extend([
                f'resource "aws_elasticache_cluster" "{r_id}" {{',
                f'  cluster_id           = "{r_name}"',
                '  engine               = "redis"',
                '  node_type            = "cache.t3.micro"',
                '  num_cache_nodes      = 1',
                '  parameter_group_name = "default.redis7"',
                '  port                 = 6379',
                '  security_group_ids   = [aws_security_group.data_sg.id]',
                '  tags = {',
                f'    Name        = "{r_name}"',
                f'    CMIR_ID     = "{r.get("id")}"',
                '    ManagedBy   = "CloudMove"',
                '  }',
                '}',
                '',
            ])
        elif r_type == "aws_s3_bucket":
            lines.extend([
                f'resource "aws_s3_bucket" "{r_id}" {{',
                f'  bucket = "cloudmove-{r_name}"',
                '  tags = {',
                f'    Name        = "{r_name}"',
                f'    CMIR_ID     = "{r.get("id")}"',
                '    ManagedBy   = "CloudMove"',
                '  }',
                '}',
                '',
            ])
        elif r_type == "aws_eks_cluster":
            lines.extend([
                f'resource "aws_eks_cluster" "{r_id}" {{',
                f'  name     = "{r_name}"',
                '  role_arn = "arn:aws:iam::123456789012:role/eks-cluster-role"',
                '  vpc_config {',
                '    subnet_ids = [aws_subnet.private_subnet_a.id, aws_subnet.private_subnet_b.id]',
                '  }',
                '  tags = {',
                f'    Name        = "{r_name}"',
                f'    CMIR_ID     = "{r.get("id")}"',
                '    ManagedBy   = "CloudMove"',
                '  }',
                '}',
                '',
            ])
        elif r_type not in ("aws_vpc", "aws_subnet", "aws_security_group"):
            # Generic fallback resource definition to handle ANY custom CMIR resource type
            lines.extend([
                f'resource "aws_instance" "{r_id}" {{',
                '  ami           = "ami-0c55b159cbfafe1f0"',
                '  instance_type = "t3.micro"',
                '  subnet_id     = aws_subnet.public_subnet.id',
                '  tags = {',
                f'    Name        = "{r_name}"',
                f'    CMIR_Type   = "{cmir_type}"',
                f'    CMIR_ID     = "{r.get("id")}"',
                '    ManagedBy   = "CloudMove"',
                '  }',
                '}',
                '',
            ])

    return "\n".join(lines)


def generate_azure_terraform(resources: List[Dict[str, Any]]) -> str:
    lines = [
        '# AUTOMATICALLY GENERATED BY CLOUDMOVE MIGRATION ENGINE (AZURE TARGET)',
        'terraform {',
        '  required_providers {',
        '    azurerm = {',
        '      source  = "hashicorp/azurerm"',
        '      version = "~> 3.0"',
        '    }',
        '  }',
        '}',
        'provider "azurerm" {',
        '  features {}',
        '}',
        '',
        'resource "azurerm_resource_group" "rg" {',
        '  name     = "cloudmove-target-rg"',
        '  location = "East US"',
        '}',
        '',
    ]
    for r in resources:
        r_id = r.get("safe_id", r.get("id").replace("-", "_"))
        r_name = r.get("safe_name", r.get("name"))
        lines.extend([
            f'# Azure Resource: {r_name}',
            f'resource "azurerm_linux_virtual_machine" "{r_id}" {{',
            f'  name                = "{r_name}"',
            '  resource_group_name = azurerm_resource_group.rg.name',
            '  location            = azurerm_resource_group.rg.location',
            '  size                = "Standard_B1s"',
            '  admin_username      = "adminuser"',
            '  tags = {',
            f'    CMIR_ID   = "{r.get("id")}"',
            '    ManagedBy = "CloudMove"',
            '  }',
            '}',
            '',
        ])
    return "\n".join(lines)


def generate_k8s_manifests(resources: List[Dict[str, Any]]) -> str:
    manifests = []
    for r in resources:
        r_name = r.get("safe_name", r.get("name"))
        manifests.append(f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {r_name}
  labels:
    app: {r_name}
    managed-by: cloudmove
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {r_name}
  template:
    metadata:
      labels:
        app: {r_name}
    spec:
      containers:
      - name: {r_name}
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {r_name}-svc
spec:
  selector:
    app: {r_name}
  ports:
  - port: 80
    targetPort: 80
---""")
    return "\n".join(manifests)